from . import res_partner
from . import buyer_contract
from . import barging_approval
from . import sales_plan
from . import sales_shipping
from . import barge_detail
from . import quality_barge
from . import product_details
from . import validation
from . import product
from . import master_iup
